# ============================================================
# THIS FILE IS UNUSED
# ============================================================
# Backend CI is defined in .ci/backend.yml and included by the
# root .gitlab-ci.yml pipeline orchestration.
#
# DO NOT add jobs here. All CI logic must remain centralized.
# This file is kept for reference only.
# ============================================================

# --- ORIGINAL BACKEND CI (COMMENTED OUT - NOT INTEGRATED) ---
# The following was the backend developer's standalone pipeline.
# It has been superseded by .ci/backend.yml integration.

# stages:
#   - build
#   - unit_test      
#   - image          
#   - deploy_staging 
#   - integration_test 
#   - deploy_prod    

# variables:
#   DOCKER_HOST: tcp://docker:2375
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_DRIVER: overlay2
#   CI_REGISTRY: "192.168.56.10:5050"
#   CI_REGISTRY_IMAGE: "192.168.56.10:5050/root/e4l"
#   MYSQL_ROOT_PASSWORD: "12345678"
#   MYSQL_USERNAME: "root"

# backend_unit_tests:
#   stage: unit_test
#   image: gradle:8.5-jdk17
#   script:
#     - cd backend/backend_code
#     - chmod +x gradlew
#     - ./gradlew clean test
#   artifacts:
#     when: always
#     paths:
#       - backend/backend_code/build/reports/tests/test/
#     reports:
#       junit: backend/backend_code/build/test-results/test/**/TEST-*.xml

# backend_image_build:
#   stage: image
#   image: docker:24-cli
#   services:
#     - name: docker:24-dind
#       command: ["--insecure-registry=192.168.56.10:5050"]
#   before_script:
#     - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
#   script:
#     - cd backend/backend_code
#     - docker build -t ${CI_REGISTRY_IMAGE}/e4l-backend:latest .
#     - docker push ${CI_REGISTRY_IMAGE}/e4l-backend:latest
#   needs: ["backend_unit_tests"]

# deploy_backend_staging:
#   stage: deploy_staging
#   image: docker:24-cli
#   services:
#     - name: docker:24-dind
#       command: ["--insecure-registry=192.168.56.10:5050"]
#   script:
#     - cd backend/backend_code/docker
#     - docker compose -f docker-compose.db.yml -f docker-compose.backend.staging.yml down -v || true
#     - docker network create e4l-db-net || true
#     - docker compose -f docker-compose.db.yml -f docker-compose.backend.staging.yml up -d
#   environment:
#     name: staging

# backend_staging_integration_check:
#   stage: integration_test
#   image: docker:24-cli
#   services:
#     - name: docker:24-dind
#   script:
#     - echo "Waiting for backend to initialize..."
#     - sleep 30
#     - docker exec e4l-db mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "SHOW DATABASES;" | grep -E "e4l_staging|e4l_prod"
#     - docker logs e4l-backend-staging | grep -q "Started Main"
#   needs: ["deploy_backend_staging"]
